name: Verify Pull Request

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]

jobs:
  format:
    name: Flutter Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed .

  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze lib

  tests:
    name: Flutter Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Format tests
        run: |
          flutter pub global activate remove_from_coverage
          remove_from_coverage -f coverage/lcov.info -r '\bshaders\b'
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: coverage/lcov.info
          min_coverage: 40
          exclude: 'repositories/'
